// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProjectBidClient is the client API for ProjectBid service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectBidClient interface {
	Bid(ctx context.Context, in *Amount, opts ...grpc.CallOption) (*Ack, error)
	Result(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Outcome, error)
}

type projectBidClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectBidClient(cc grpc.ClientConnInterface) ProjectBidClient {
	return &projectBidClient{cc}
}

func (c *projectBidClient) Bid(ctx context.Context, in *Amount, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/proto.project_bid/bid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectBidClient) Result(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/proto.project_bid/result", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectBidServer is the server API for ProjectBid service.
// All implementations must embed UnimplementedProjectBidServer
// for forward compatibility
type ProjectBidServer interface {
	Bid(context.Context, *Amount) (*Ack, error)
	Result(context.Context, *Message) (*Outcome, error)
	mustEmbedUnimplementedProjectBidServer()
}

// UnimplementedProjectBidServer must be embedded to have forward compatible implementations.
type UnimplementedProjectBidServer struct {
}

func (UnimplementedProjectBidServer) Bid(context.Context, *Amount) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bid not implemented")
}
func (UnimplementedProjectBidServer) Result(context.Context, *Message) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Result not implemented")
}
func (UnimplementedProjectBidServer) mustEmbedUnimplementedProjectBidServer() {}

// UnsafeProjectBidServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectBidServer will
// result in compilation errors.
type UnsafeProjectBidServer interface {
	mustEmbedUnimplementedProjectBidServer()
}

func RegisterProjectBidServer(s grpc.ServiceRegistrar, srv ProjectBidServer) {
	s.RegisterService(&ProjectBid_ServiceDesc, srv)
}

func _ProjectBid_Bid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Amount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectBidServer).Bid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.project_bid/bid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectBidServer).Bid(ctx, req.(*Amount))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectBid_Result_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectBidServer).Result(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.project_bid/result",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectBidServer).Result(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectBid_ServiceDesc is the grpc.ServiceDesc for ProjectBid service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectBid_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.project_bid",
	HandlerType: (*ProjectBidServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "bid",
			Handler:    _ProjectBid_Bid_Handler,
		},
		{
			MethodName: "result",
			Handler:    _ProjectBid_Result_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
